version: "3.9"

services:
  database:
    image: postgres:15.1
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - '5433:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  app:
    depends_on:
      - database
    build: .
    restart: always
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/$POSTGRES_DB?useSSL=false
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
#      SPRING_APPLICATION_JSON: '{
#              "spring.datasource.url"  : "jdbc:postgresql://database:5432/$POSTGRES_DB?useSSL=false",
#              "spring.datasource.username" : "$POSTGRES_USER",
#              "spring.datasource.password" : "$POSTGRES_PASSWORD",
#              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
#              "spring.jpa.hibernate.ddl-auto" : "none"
#            }'
    volumes:
      - .m2:/root/.m2
volumes:
  db:
  m2:
