spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myDB?useSSL=false
    username: name
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  jwt:
#    secret: *******